# Nome do fluxo de trabalho para fácil identificação no GitHub
name: Reiniciar API Diariamente

on:
  schedule:
    # Agenda para rodar todos os dias às 6:00 UTC.
    # IMPORTANTE: O GitHub Actions usa o horário UTC.
    # 3:00 da manhã no Brasil (UTC-3) corresponde a 6:00 da manhã em UTC.
    - cron: '0 6 * * *'

jobs:
  # Nome do trabalho
  restart-job:
    # O tipo de máquina que o trabalho vai rodar
    runs-on: ubuntu-latest

    steps:
      # Nome do passo
      - name: Chamar a API de reinício do EasyPanel
        run: |
          curl --request POST \
          --url 'http://62.171.155.205:3000/api/trpc/services.app.restartService' \
          --header 'Authorization: Bearer ${{ secrets.EASYPANEL_API_TOKEN }}'
